math=float(input("Enter mark of Math = "))
english=float(input("Enter mark of English = "))
hindi=float(input("Enter mark of Hindi = "))
science=float(input("Enter mark of Science = "))
sanskrit=float(input("Enter mark of Sanskrit = "))
s=(math+english+hindi+science+sanskrit)
print("Sum of Marks = ",s)
print("Average of Marks =",s/5)
print("Percentage of Marks =",s*100/500,"%")
